services:
  - type: web
    name: vulcain-backend
    runtime: node # Correction : utilise 'runtime' au lieu de 'env'
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        value: file:/data/vulcain_core.db
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production
    disk: # Le champ correct est 'disk'
      name: vulcain-data
      mountPath: /data
      sizeGB: 1